title: Button
context:
  text: Subscribe
variants:
- name: secondary
  context:
    class: btn--secondary
- name: small
  context:
    class: btn--small
- name: large
  context:
    class: btn--large
