variants:
  - name: list
    context:
      class: list
  - name: list lg
    context:
      class: list list--lg
  - name: list-inline
    context:
      class: list-inline
  - name: list-inline and list--lg
    context:
      class: list-inline list-inline--lg
  - name: list-dash
    context:
      class: list-dash
