title: Button
context:
  text: Subscribe
variants:
- name: Secondary
  context:
    class: button--secondary
- name: Small
  context:
    class: button--small
- name: Large
  context:
    class: button--large
